import {executable} from './programs.js';
import {ICONS} from './symbols.js';
import {FAMILIES,THEMES,safeJson,LIMITS} from './config.js';
import {digest} from '../engine.js';
const LICENSE_NOTICE="<!-- Bundled program and icons licenses:\nMIT License\n\nCopyright (c) 2026 scasella\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the \"Software\"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.\n\nMIT License\n\nCopyright (c) 2020 Phosphor Icons\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the \"Software\"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.\n-->";
export const EXPORTER='groundwork-offline-export/1';
export const escapeXml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
export function patternSvg(artifact){
 const cells=executable(artifact)();let marks='';
 for(let y=0;y<32;y++)for(let x=0;x<32;x++)marks+=`<rect x="${x*10}" y="${y*10}" width="10" height="10" fill="${artifact.config.palette[cells[(y%8)*8+x%8]]}"/>`;
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 320" role="img" aria-labelledby="pattern-title"><title id="pattern-title">${escapeXml(artifact.config.title||'Pattern postcard')}</title>${marks}</svg>`;
}
const CSS=String.raw`*{box-sizing:border-box}body{margin:0;padding:24px;background:#10191c;color:#eff7f4;font:16px system-ui,sans-serif;line-height:1.6}main{max-width:760px;margin:auto}h1{font-size:clamp(28px,5vw,44px);line-height:1.2;overflow-wrap:anywhere}h2{line-height:1.35;overflow-wrap:anywhere}p{white-space:pre-wrap;overflow-wrap:anywhere}button{font:inherit;cursor:pointer;border:1px solid #8aa99e;border-radius:10px;padding:12px 18px;background:#163c35;color:#eff7f4;min-height:48px}button:hover:not(:disabled){filter:brightness(1.25)}button:focus-visible{outline:3px solid #ffe3aa;outline-offset:4px}button:disabled{opacity:.5;cursor:default}.board{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:24px 0}.card{min-height:100px;padding:12px;display:grid;place-items:center}.card svg{width:54px;max-width:100%;height:auto}.card[data-up=true]{background:var(--ink);color:var(--paper)}.pots{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.pot{text-align:center;padding:20px 10px;background:var(--paper);color:var(--ink);border-radius:18px}.pot svg{width:64px;max-width:100%;height:auto}.pot h2{font-size:20px}.controls{display:flex;flex-wrap:wrap;gap:12px;margin:20px 0}.scene{padding:28px;background:var(--paper);color:var(--ink);border-radius:20px}.scene button{display:block;width:100%;text-align:left;margin:12px 0}#status{min-height:26px}.pattern{max-width:560px;margin:24px auto}.pattern svg{width:100%;display:block}.note,footer{color:#b0c6bc;font-size:13px}footer{border-top:1px solid #3a514b;padding-top:24px;margin-top:32px}a{color:#9ce2cc}@media(max-width:480px){body{padding:18px}.board{gap:8px}.card{padding:8px;min-height:78px}.pots{grid-template-columns:1fr}.scene{padding:20px}}@media print{body{background:white;color:black}.controls,footer,.note{display:none}.pattern{max-width:160mm}button{color:black}}`;
// This renderer is literal too: exports must have stable byte identities across builds.
const RUNTIME=String.raw`
const root=document.querySelector('#play'),status=document.querySelector('#status');
let state=run(null,{type:'init'});
function node(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;}
function icon(name){const el=node('span');el.innerHTML=ICONS[name];return el;}
function button(label,action,disabled=false,key=label){const el=node('button',label);el.type='button';el.disabled=disabled;el.dataset.key=key;el.onclick=event=>{if(event.detail>1)return;state=run(state,action);render(key);};return el;}
function render(focusKey){
 root.replaceChildren();
 if(KIND==='memory'){
  const deck=run(null,{type:'deck'}),board=node('div',undefined,'board');
  deck.forEach((symbol,i)=>{const up=!!(state.matched&(1<<i))||state.open.includes(i),b=button('',{type:'select',index:i},false,'card'+i);b.className='card';b.dataset.up=up;b.setAttribute('aria-label','Card '+(i+1)+(up?': '+symbol:': face down'));b.setAttribute('aria-pressed',String(up));b.setAttribute('aria-disabled',String(up||state.pending));b.append(up?icon(symbol):node('span',String(i+1)));board.append(b);});root.append(board);
  status.textContent=state.matched===255?'All four pairs found!':state.pending?'Different symbols. Choose Next turn when you are ready.':state.open.length?'Choose one more card.':'Choose two cards.';
  const controls=node('div',undefined,'controls');controls.append(button('Next turn',{type:'next'},!state.pending),button('Play this board again',{type:'reset'}));root.append(controls);
 }else if(KIND==='story'){
  const scene=CONFIG.scenes[state.node],panel=node('section',undefined,'scene');panel.append(node('h2',scene.title),node('p',scene.body));scene.choices.forEach((c,i)=>panel.append(button(c.label||'Choice '+(i+1),{type:'choose',index:i},false,'choice'+i)));root.append(panel);
  status.textContent=scene.choices.length?'Choose where your story goes.':'The end. Try another path whenever you like.';
  const controls=node('div',undefined,'controls');if(CONFIG.navigation==='back')controls.append(button('Back',{type:'back'},!state.history.length));controls.append(button('Start over',{type:'reset'}));root.append(controls);
 }else if(KIND==='garden'){
  const pots=node('div',undefined,'pots');CONFIG.pots.forEach((p,i)=>{const pot=node('section',undefined,'pot');pot.append(icon(FAMILIES[p.family][state.stages[i]]),node('h2',p.name||'Creature '+(i+1)),node('p',['A little seed','Growing curious','Fully grown'][state.stages[i]]),button('Water '+(p.name||'creature '+(i+1)),{type:'water',index:i},state.stages[i]===2||(CONFIG.water==='shared'&&!state.water),'water'+i));pots.append(pot);});root.append(pots);
  status.textContent=CONFIG.water==='shared'?state.water+' of 3 shared drops left. Next turn refills them.':'Water as often as you like. Each creature has three stages.';
  const controls=node('div',undefined,'controls');if(CONFIG.water==='shared')controls.append(button('Next turn · refill water',{type:'next'}));controls.append(button('Plant again',{type:'reset'}));root.append(controls);
 }
 if(focusKey&&KIND==='story'){const heading=root.querySelector('h2');heading.tabIndex=-1;heading.focus();}
 else if(focusKey){const target=[...root.querySelectorAll('button')].find(b=>b.dataset.key===focusKey&&!b.disabled);if(target)target.focus();else root.querySelector('button:not(:disabled)')?.focus();}
}
if(KIND==='pattern'){root.className='pattern';root.innerHTML=ART;status.textContent='Your repeating pattern. Use your browser’s Print command to make a postcard.';}else render();
`;
export function htmlExport(artifact){
 executable(artifact);const {kind,config}=artifact,colors=THEMES[config.theme]||THEMES.mint;
 return `<!doctype html>\n${LICENSE_NOTICE}\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="groundwork-artifact" content="${artifact.id}"><title>${escapeXml(config.title||'My Groundwork project')}</title><style>${CSS}</style></head><body style="--paper:${colors[0]};--ink:${colors[1]}"><main><p class="note">MADE WITH GROUNDWORK · OFFLINE ${kind==='pattern'?'ARTWORK':'PLAY'}</p><h1>${escapeXml(config.title||'My Groundwork project')}</h1><p id="status" role="status" aria-live="polite"></p><div id="play"></div><noscript>This project needs JavaScript enabled to play.</noscript><footer>${escapeXml(LIMITS[kind])}<p>No network connection or sign-in needed. Play resets when this page is reopened.</p><p>Source revision ${artifact.revision} · ${artifact.id.slice(0,12)}. This export is not a certificate or a recorded human decision.</p></footer></main><script type="module">\n${artifact.source}\nconst KIND=${safeJson(kind)},ICONS=${safeJson(ICONS)},FAMILIES=${safeJson(FAMILIES)},ART=${safeJson(kind==='pattern'?patternSvg(artifact):'')};\n${RUNTIME}\n</script></body></html>\n`;
}
export function exportIdentity(artifact){return {exporter:EXPORTER,html:digest(htmlExport(artifact)),...(artifact.kind==='pattern'?{svg:digest(patternSvg(artifact))}:{})};}
export function editableExport(artifact){return JSON.stringify({format:'groundwork-project/1',kind:artifact.kind,config:artifact.config},null,2);}
export function filename(artifact,extension){const slug=artifact.config.title.normalize('NFKD').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').slice(0,50).toLowerCase()||artifact.kind;return `${slug}-r${artifact.revision}.${extension}`;}
