import React,{useState,useEffect,useMemo,useRef} from 'react';
import {Stack,ArrowRight,ArrowLeft,DownloadSimple,CheckCircle,BookOpen} from '@phosphor-icons/react';
import {Modal} from '../App.jsx';
import {KINDS,TITLES,defaults,SYMBOLS,FAMILIES,THEMES,ruleSummary,LIMITS} from './config.js';
import {artifactFor} from './programs.js';
import {currency,canKeep} from './engine.js';
import {htmlExport,patternSvg,editableExport,filename} from './exports.js';
import {STUDIO_KEY,loadStudio,newStudio,currentArtifact,currentReport,editProject,checkDraft,keepProject,isKept,importProject,historyLabel} from './session.js';
import {Preview,Symbol} from './Preview.jsx';
import './studio.css';
const DESCRIPTIONS={pattern:'Make one mark. Watch it become your signature pattern.',memory:'Make a memory game about your favorite things.',story:'Make a story a friend can play.',garden:'Grow a pocket world full of creatures you named.'};
const DELIVERABLES={pattern:'SVG artwork + printable page',memory:'An offline memory game',story:'A playable offline story',garden:'An offline garden toy'};
const NEXT={pattern:'Change a colored square in the editor. Watch the whole postcard change.',memory:'Try turning over two cards. Then choose the four symbols for your game.',story:'Play the opening. Then rewrite one scene and try its choices.',garden:'Water a seed. Then name your creatures and choose how water works.'};
function download(name,body,type='application/json'){const url=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Field({label,children}){return <label className="studio-field"><span>{label}</span>{children}</label>;}
function Theme({config,onChange}){return <Field label="Color mood"><select value={config.theme} onChange={e=>onChange({...config,theme:e.target.value})}>{Object.keys(THEMES).map(t=><option key={t} value={t}>{t[0].toUpperCase()+t.slice(1)}</option>)}</select></Field>;}
function PatternEditor({c,change}){const [ink,setInk]=useState(1);return <><h3>1. Make your mark</h3><p>Pick an ink, then color a square. This left half becomes a complete repeating tile.</p><div className="pattern-inks" aria-label="Drawing ink">{c.palette.map((color,i)=><button key={i} type="button" style={{background:color}} aria-label={`Draw with ink ${i+1}`} aria-pressed={ink===i} onClick={()=>setInk(i)}><span>{i+1}</span></button>)}</div><div className="pattern-seed" aria-label="Editable left half of the tile">{c.seed.map((color,i)=><button key={i} style={{background:c.palette[color]}} aria-label={`Row ${Math.floor(i/4)+1}, column ${i%4+1}, ink ${color+1}`} onClick={()=>change({...c,seed:c.seed.map((v,j)=>i===j?ink:v)})}/>)}</div><details className="studio-options"><summary>2. Change your palette</summary><div className="color-inputs">{c.palette.map((color,i)=><Field key={i} label={`Ink ${i+1}`}><input type="color" value={color} onChange={e=>change({...c,palette:c.palette.map((v,j)=>i===j?e.target.value:v)})}/></Field>)}</div></details><Field label="3. Complete the tile"><select value={c.symmetry} onChange={e=>change({...c,symmetry:e.target.value})}><option value="mirror">Mirror · reflect left to right</option><option value="turn">Half-turn · rotate 180°</option></select></Field><p className="studio-hint">Mirror keeps a mark on the same row. Half-turn places its partner on the opposite row too.</p></>;}
function MemoryEditor({c,change}){return <><h3>1. Choose your four pairs</h3><p>Choose four different symbols. Each appears twice.</p><div className="symbol-picker" aria-label="Your four symbols">{c.symbols.map(symbol=><div key={symbol}><Symbol name={symbol}/><span>{symbol}</span></div>)}</div><div className="pair-selects">{c.symbols.map((symbol,i)=><Field key={i} label={`Pair ${i+1}`}><select value={symbol} onChange={e=>change({...c,symbols:c.symbols.map((s,j)=>i===j?e.target.value:s)})}>{SYMBOLS.map(s=><option key={s} value={s} disabled={c.symbols.includes(s)&&s!==symbol}>{s}</option>)}</select></Field>)}</div><h3>2. Make it yours</h3><Theme config={c} onChange={change}/><button className="btn secondary" onClick={()=>change({...c,seed:(c.seed+1)%65536})}>Try a new arrangement</button><p className="studio-hint">The chosen board stays the same when restarted. Mismatched cards wait for Next turn, so nobody has to rush.</p></>;}
function StoryEditor({c,change}){const [sceneId,setSceneId]=useState('start'),scene=c.scenes[sceneId];const update=next=>change({...c,scenes:{...c.scenes,[sceneId]:next}});return <><h3>1. Write a little world</h3><Field label="Scene to edit"><select value={sceneId} onChange={e=>setSceneId(e.target.value)}>{Object.keys(c.scenes).map((id,i)=><option value={id} key={id}>{['Opening','Scene A','Scene B','Ending A','Ending B'][i]}</option>)}</select></Field><Field label="Scene heading"><input maxLength={60} value={scene.title} onChange={e=>update({...scene,title:e.target.value})}/></Field><Field label="What happens here?"><textarea rows={4} maxLength={500} value={scene.body} onChange={e=>update({...scene,body:e.target.value})}/></Field>{scene.choices.map((choice,i)=><div className="story-choice-editor" key={i}><Field label={`Choice ${i+1} says`}><input maxLength={60} value={choice.label} onChange={e=>update({...scene,choices:scene.choices.map((v,j)=>i===j?{...v,label:e.target.value}:v)})}/></Field><Field label={`Choice ${i+1} leads to`}><select value={choice.to} onChange={e=>update({...scene,choices:scene.choices.map((v,j)=>i===j?{...v,to:e.target.value}:v)})}>{(sceneId==='start'?['left','right','endA','endB']:['endA','endB']).map(id=><option value={id} key={id}>{id==='left'?'Scene A':id==='right'?'Scene B':id==='endA'?'Ending A':'Ending B'} · {c.scenes[id].title}</option>)}</select></Field></div>)}<h3>2. Set the reading experience</h3><Theme config={c} onChange={change}/><Field label="Trying another route"><select value={c.navigation} onChange={e=>change({...c,navigation:e.target.value})}><option value="back">Let readers go Back</option><option value="restart">Readers start over</option></select></Field><p className="studio-hint">Forward choices always reach an ending within two steps. Back is a separate action.</p></>;}
function GardenEditor({c,change}){return <><h3>1. Meet your creatures</h3>{c.pots.map((p,i)=><div className="creature-editor" key={i}><Field label={`Creature ${i+1} name`}><input maxLength={24} value={p.name} onChange={e=>change({...c,pots:c.pots.map((v,j)=>i===j?{...v,name:e.target.value}:v)})}/></Field><Field label={`Creature ${i+1} family`}><select value={p.family} onChange={e=>change({...c,pots:c.pots.map((v,j)=>i===j?{...v,family:e.target.value}:v)})}>{Object.keys(FAMILIES).map(f=><option key={f} value={f}>{f==='bloom'?'Seed → sprout → flower':f==='flutter'?'Seed → leaf → butterfly':'Seed → moon → planet'}</option>)}</select></Field></div>)}<h3>2. Choose your pocket world</h3><Theme config={c} onChange={change}/><Field label="Water supply"><select value={c.water} onChange={e=>change({...c,water:e.target.value})}><option value="free">Unlimited · grow at your own pace</option><option value="shared">3 shared drops each turn</option></select></Field><p className="studio-hint">Nothing withers. With shared water, Next turn refills your three drops whenever you choose.</p></>;}
const EDITORS={pattern:PatternEditor,memory:MemoryEditor,story:StoryEditor,garden:GardenEditor};
function Cover({kind}){const a=artifactFor(kind,defaults(kind));if(kind==='pattern')return <div className="shelf-pattern" dangerouslySetInnerHTML={{__html:patternSvg(a)}}/>;if(kind==='memory')return <div className="shelf-symbols">{a.config.symbols.map(s=><Symbol key={s} name={s}/>)}</div>;if(kind==='story')return <div className="shelf-story"><BookOpen size={55} weight="duotone"/><span>A letter at your door.</span><small>Two choices. A world of your own.</small></div>;return <div className="shelf-garden">{['flower','butterfly','planet'].map(s=><Symbol key={s} name={s}/>)}</div>;}
export function Studio({storageKey=STUDIO_KEY,accountControls,initialKind}={}){
 const [loaded]=useState(()=>{try{return loadStudio(window.localStorage,storageKey);}catch(error){return {data:newStudio(),recovery:{raw:null,message:error.message}};}}),[data,setData]=useState(loaded.data),[recovery,setRecovery]=useState(loaded.recovery),[saved,setSaved]=useState(false);
 const route=()=>{const q=new URLSearchParams(window.location.search).get('studio');return KINDS.includes(q)?q:null;};
 const [selected,setSelected]=useState(initialKind||route),[notice,setNotice]=useState(''),[modal,setModal]=useState(null),[ack,setAck]=useState(false);
 const ref=useRef(data);ref.current=data;const importRef=useRef();
 useEffect(()=>{if(recovery){setSaved(false);return;}try{localStorage.setItem(storageKey,JSON.stringify(data));setSaved(true);}catch{setSaved(false);}},[data,storageKey,recovery]);
 useEffect(()=>{const pop=()=>{setSelected(route());setAck(false);setNotice('');};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[]);
 function select(kind){setSelected(kind);setAck(false);setNotice('');const url=new URL(window.location.href);url.searchParams.set('studio',kind||'1');url.searchParams.delete('example');url.hash='';window.history.pushState(null,'',url);window.scrollTo(0,0);}
 function update(kind,fn){try{const old=ref.current,next={...old,projects:{...old.projects,[kind]:fn(old.projects[kind])}};ref.current=next;setData(next);setAck(false);setNotice('');}catch(e){setNotice(e.message);}}
 const p=selected?data.projects[selected]:null,artifact=useMemo(()=>p?currentArtifact(p):null,[p?.kind,p?.revision,p?.config]),report=p?currentReport(p):null;
 const fresh=!!report&&currency(report,artifact)==='current',passed=fresh&&canKeep(report,artifact),kept=p&&isKept(p);
 const change=c=>update(selected,old=>editProject(old,c));
 function exportFile(format,a=artifact){if(format==='html')download(filename(a,'html'),htmlExport(a),'text/html');if(format==='svg')download(filename(a,'svg'),patternSvg(a),'image/svg+xml');if(format==='json')download(filename(a,'json'),editableExport(a));if(format==='mjs')download(filename(a,'mjs'),a.source,'text/javascript');}
 const exportWorkspace=()=>download('groundwork-starter-history.json',JSON.stringify(ref.current,null,2));
 async function chooseImport(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;try{if(file.size>100000)throw Error('Choose a project smaller than 100 KB');const value=importProject(await file.text());setModal({type:'import',value});}catch(e){setNotice(e.message);}}
 const Editor=selected?EDITORS[selected]:null;
 return <div className="beginner-app studio-app"><header className="lesson-topbar"><a className="lesson-brand" href="?studio=1"><Stack size={27}/><strong>Groundwork</strong><span>MAKE SOMETHING YOURS</span></a><div className="lesson-topbar-actions">{accountControls}<a className="studio-link" href="?">Beginner lessons</a></div></header><main className="studio-main">
  <input ref={importRef} hidden type="file" accept=".json,application/json" aria-label="Open editable project" onChange={chooseImport}/>
  {(!saved||recovery)&&<div className="notice amber" role="alert"><div><strong>{recovery?'Saved projects could not be restored. The original has not been overwritten.':'Projects are not saved. Download your work before closing.'}</strong><div className="actions"><button className="text-btn" onClick={exportWorkspace}>Download current workspace</button>{recovery&&<><button className="text-btn" onClick={()=>download('groundwork-unrestored-starters.txt',recovery.raw||recovery.message,'text/plain')}>Download original data</button><button className="text-btn" onClick={()=>setModal({type:'recover'})}>Review recovery options</button></>}</div></div></div>}
  {notice&&<p className="notice amber" role="alert">{notice}</p>}
  {!selected?<><div className="studio-intro"><p className="eyebrow">YOUR NEXT SMALL CREATION</p><h1>Start with something working.<br/><em>Make it yours.</em></h1><p>Play, personalize, and take something home. Every project comes with a real check of its small set of rules.</p><button className="text-btn" onClick={()=>importRef.current.click()}>Open an editable project</button></div><div className="project-shelf">{KINDS.map(kind=><article className={`shelf-card shelf-${kind}`} key={kind}><div className="shelf-cover" aria-hidden="true"><Cover kind={kind}/></div><div className="shelf-copy"><p className="eyebrow">{DELIVERABLES[kind]}</p><h2>{TITLES[kind]}</h2><p>{DESCRIPTIONS[kind]}</p><button className="btn primary" onClick={()=>select(kind)}>{data.projects[kind].revision>1||data.projects[kind].reports.length?'Continue creating':'Make it yours'} <ArrowRight size={17}/><span className="sr-only"> · {TITLES[kind]}</span></button></div></article>)}</div><p className="studio-footnote">No blank canvas, no code required. Prepared building blocks, real checks, and files you can keep. Your projects stay in this browser; sign-in does not sync them.</p></>:<>
  <button className="text-btn studio-back" onClick={()=>select(null)}><ArrowLeft size={16}/>All starter projects</button>
  <div className="studio-heading"><div><p className="eyebrow">{TITLES[selected]}</p><h1>Make a little {selected==='pattern'?'art':selected==='memory'?'game':selected==='story'?'adventure':'world'}.</h1><p>{NEXT[selected]}</p></div><span className="studio-draft">{kept?'Checked version kept':passed?'Checked · ready to review':'Your draft'} · revision {p.revision}</span></div>
  <nav className="studio-jumps" aria-label="Project sections"><a href="#project-preview">Try it</a><a href="#project-editor">Personalize ↓</a><a href="#project-check">Check & keep</a></nav><div className="studio-workbench"><section id="project-editor" className="studio-editor" aria-label="Personalize your project"><Field label="Give it a title"><input value={p.config.title} maxLength={60} onChange={e=>change({...p.config,title:e.target.value})}/></Field><Editor c={p.config} change={change}/><a className="studio-mobile-preview-link" href="#project-preview">Try your changes ↑</a></section><section id="project-preview" className="studio-preview" aria-label="Working project preview"><div className="studio-preview-label"><span>TRY YOUR CREATION</span><small>Edits restart the preview</small></div><Preview artifact={artifact} key={artifact.id}/><p className="studio-preview-note">{DELIVERABLES[selected]}. The preview, check, and download use this same prepared program.</p></section></div>
  <section id="project-check" className="studio-review" aria-label="Check and keep"><div><p className="eyebrow">WHEN IT FEELS LIKE YOURS</p><h2>Check the rules. Keep your creation.</h2><p>{ruleSummary(selected,p.config)}</p>{report&&!fresh&&<div className="studio-stale"><strong>Your settings changed. The earlier {report.outcome} result covers an older version.</strong><p>{ruleSummary(selected,report.contract.config)!==ruleSummary(selected,p.config)?`Previously: ${ruleSummary(selected,report.contract.config)}`:'Your earlier design and its check are still available in version history.'}</p><p>This is a new design choice, not a claim that the old program was wrong. Check these settings before keeping a new checked version.</p></div>}<div className="actions"><button className="btn primary" onClick={()=>update(selected,checkDraft)}><CheckCircle size={18}/>{passed?'Check these settings again':'Check these settings'}</button><small>Records the settings you choose to check.</small></div></div><div className="studio-result" aria-live="polite">
   <p className="eyebrow">{fresh?report.outcome==='passed'?'RULE CHECK PASSED':report.outcome==='failed'?'RULE CHECK FAILED':'CHECK INCOMPLETE':'NOT CHECKED YET'}</p><h3>{kept?'You kept this version.':passed?'The supported rules matched.':fresh?report.message:'Try it, then check when you are ready.'}</h3>{fresh&&<p>{report.states} reachable {report.states===1?'state':'states'} · {report.transitions} {selected==='pattern'?'tile cells':'transitions'} checked{selected==='pattern'?' · SVG cells compared separately':''}.</p>}<p className="studio-limit">{LIMITS[selected]}</p>{passed&&!kept&&<label className="studio-ack"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/><span>I tried this version and understand what the check does not establish.</span></label>}<button className="btn secondary" disabled={!passed||(!ack&&!kept)||kept} onClick={()=>update(selected,keepProject)}>{kept?'Kept in version history':'Keep checked version'}</button>{!passed&&<small>Available after a complete, current check.</small>}{passed&&!kept&&!ack&&<small>Review the limits and tick the box first.</small>}
  </div></section>
  <section className="studio-downloads"><div><h2>Take it with you.</h2><p>{selected==='pattern'?'Save your artwork, or open the HTML page and use your browser’s Print command.':'Open your downloaded HTML file in a browser to play offline. No sign-in or network needed.'} Download editable settings to continue creating here later.</p><small>Downloads contain the current draft. Downloading does not record acceptance or turn a draft into a checked version.</small></div><div className="studio-download-buttons"><button className="btn primary" onClick={()=>exportFile('html')}><DownloadSimple size={18}/>{selected==='pattern'?'Download print page':'Download playable HTML'}</button>{selected==='pattern'&&<button className="btn secondary" onClick={()=>exportFile('svg')}>Download SVG artwork</button>}<button className="btn secondary" onClick={()=>exportFile('json')}>Download editable project</button></div></section>
  <details className="studio-details"><summary>Version history, exact program, and check details</summary><p>Changing settings creates a new draft. Earlier checks and keep decisions remain historical. This browser’s editable storage is not a signed audit trail.</p><details><summary>Current prepared program · {artifact.id.slice(0,12)}</summary><button className="text-btn" onClick={()=>exportFile('mjs')}>Download exact module</button><pre>{artifact.source}</pre></details>{p.reports.length===0&&<p>No checks recorded yet.</p>}{p.reports.slice().reverse().map(r=><article className="studio-history" key={r.id}><h3>Revision {r.artifact.revision} · {r.artifact.config.title||'Untitled'}</h3><p>{historyLabel(r,p)}{p.decisions.some(d=>d.reportId===r.id)?' · kept after review':' · no keep decision'}</p><p>{r.message}</p><div className="actions"><button className="text-btn" onClick={()=>setModal({type:'restore',report:r})}>Use these settings as a new draft</button><button className="text-btn" disabled={!r.outputs?.html} onClick={()=>download(filename(r.artifact,'html'),r.outputs.html,'text/html')}>Download checked export</button><button className="text-btn" onClick={()=>download(`groundwork-${selected}-r${r.artifact.revision}-check.json`,JSON.stringify(r,null,2))}>Download check</button></div><details><summary>Exact settings, scope, source, and evidence</summary><pre>{JSON.stringify({...r,outputs:r.outputs?{html:`${r.outputs.html.length} characters; exact bytes in the check download`,svg:r.outputs.svg?`${r.outputs.svg.length} characters`:undefined}:null},null,2)}</pre></details></article>)}</details>
  </>}
  <footer className="studio-footer"><span>{saved?'Projects saved in this browser':'Projects are not saved'} · No cloud sync</span><button className="text-btn" onClick={()=>importRef.current.click()}>Open editable project</button><button className="text-btn" onClick={exportWorkspace}>Download workspace history</button>{selected&&<button className="text-btn" onClick={()=>setModal({type:'new'})}>Start a fresh design</button>}</footer>
 </main>{modal&&<Modal title={modal.type==='recover'?'Recover your workspace':modal.type==='import'?'Open these project settings?':'Start a new draft?'} onClose={()=>setModal(null)}><p>{modal.type==='recover'?'The unreadable saved workspace will be replaced. Download the original first if you want to preserve it.':modal.type==='import'?'This replaces the current draft for this project. Only settings are imported, with no check or keep decision. Earlier checked versions remain in history.':'This replaces your current draft. Earlier checked versions and decisions remain in history.'}</p><div className="actions"><button className="btn secondary" onClick={()=>modal.type==='recover'?download('groundwork-unrestored-starters.txt',recovery?.raw||recovery?.message||'','text/plain'):exportWorkspace()}>Download before replacing</button><button className="btn primary" onClick={()=>{if(modal.type==='recover'){const next=newStudio();ref.current=next;setData(next);setRecovery(null);}else if(modal.type==='import'){update(modal.value.kind,old=>editProject(old,modal.value.config));select(modal.value.kind);}else change(modal.type==='restore'?modal.report.artifact.config:defaults(selected));setModal(null);}}>Replace draft{modal.type==='recover'?' workspace':''}</button><button className="btn ghost" onClick={()=>setModal(null)}>Cancel</button></div></Modal>}</div>;
}
