// @vitest-environment jsdom
import React from 'react';
import {test,expect,afterEach,beforeEach,vi} from 'vitest';
import {render,screen,fireEvent,cleanup,within} from '@testing-library/react';
import {Studio} from '../src/studio/Studio.jsx';
import {STUDIO_KEY} from '../src/studio/session.js';
beforeEach(()=>{vi.spyOn(window,'scrollTo').mockImplementation(()=>{});window.history.replaceState(null,'','/');});
afterEach(()=>{cleanup();localStorage.clear();vi.restoreAllMocks();});
test('the shelf contains only the four selected projects and opens a working editor',()=>{render(<Studio/>);expect(screen.getAllByRole('button',{name:/Make it yours/})).toHaveLength(4);expect(screen.queryByText('Our Little Festival')).toBe(null);fireEvent.click(screen.getByRole('button',{name:/Make it yours.*Pattern/}));expect(screen.getByLabelText('Give it a title').value).toBe('Little waves');expect(screen.getByRole('button',{name:'Keep checked version'}).disabled).toBe(true);});
for(const kind of ['pattern','memory','story','garden'])test(`${kind}: edit, check, explicitly keep, revise and refresh preserve separate history`,()=>{
 const view=render(<Studio initialKind={kind}/>);fireEvent.change(screen.getByLabelText('Give it a title'),{target:{value:'My creation'}});fireEvent.click(screen.getByRole('button',{name:'Check these settings'}));expect(screen.getByText('RULE CHECK PASSED')).toBeTruthy();expect(screen.getByRole('button',{name:'Keep checked version'}).disabled).toBe(true);fireEvent.click(screen.getByRole('checkbox',{name:/I tried this version/}));fireEvent.click(screen.getByRole('button',{name:'Keep checked version'}));expect(screen.getByText('You kept this version.')).toBeTruthy();fireEvent.change(screen.getByLabelText('Give it a title'),{target:{value:'My new creation'}});expect(screen.getByText(/earlier passed result covers an older version/)).toBeTruthy();expect(screen.getByRole('button',{name:'Keep checked version'}).disabled).toBe(true);fireEvent.click(screen.getByRole('button',{name:'Check these settings'}));expect(screen.getByRole('checkbox',{name:/I tried this version/}).checked).toBe(false);view.unmount();render(<Studio initialKind={kind}/>);expect(screen.getByLabelText('Give it a title').value).toBe('My new creation');const p=JSON.parse(localStorage.getItem(STUDIO_KEY)).projects[kind];expect(p.reports).toHaveLength(2);expect(p.decisions).toHaveLength(1);
});
test('memory UI blocks a third turn click and garden shows manual water exhaustion',()=>{
 const view=render(<Studio initialKind="memory"/>);const firstCard=screen.getByRole('button',{name:'Card 1: face down'});fireEvent.click(firstCard);fireEvent.click(firstCard);expect(screen.getByText('Choose one more card.')).toBeTruthy();const second=screen.getByRole('button',{name:'Card 2: face down'});fireEvent.click(second);expect(screen.getByText(/Different symbols/)).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Card 3: face down'}));expect(screen.getByRole('button',{name:'Card 3: face down'})).toBeTruthy();view.unmount();render(<Studio initialKind="garden"/>);fireEvent.change(screen.getByLabelText('Water supply'),{target:{value:'shared'}});fireEvent.click(screen.getByRole('button',{name:'Water Pip'}));fireEvent.click(screen.getByRole('button',{name:'Water Pip'}));fireEvent.click(screen.getByRole('button',{name:'Water Miso'}));expect(screen.getByRole('button',{name:'Water Orbit'}).disabled).toBe(true);expect(screen.getByText('0 of 3 shared drops left. Next turn refills them.')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Next turn · refill water'}));expect(screen.getByRole('button',{name:'Water Orbit'}).disabled).toBe(false);
});
test('recovery and write errors never display a false save; reset requires a deliberate dialog',()=>{
 localStorage.setItem(STUDIO_KEY,'{broken');render(<Studio initialKind="pattern"/>);expect(screen.getByText(/could not be restored/)).toBeTruthy();expect(localStorage.getItem(STUDIO_KEY)).toBe('{broken');fireEvent.click(screen.getByRole('button',{name:'Review recovery options'}));expect(screen.getByRole('dialog')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Cancel'}));expect(screen.queryByRole('dialog')).toBe(null);cleanup();localStorage.clear();vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw Error('quota');});render(<Studio initialKind="pattern"/>);expect(screen.queryByText(/Projects saved in this browser/)).toBe(null);expect(screen.getByText(/Projects are not saved. Download/)).toBeTruthy();
});
test('downloads create actual offline and editable files without a keep decision',()=>{
 const blobs=[];vi.stubGlobal('URL',class extends URL{static createObjectURL(blob){blobs.push(blob);return 'blob:test';}static revokeObjectURL(){}});vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});render(<Studio initialKind="story"/>);fireEvent.click(screen.getByRole('button',{name:'Download playable HTML'}));fireEvent.click(screen.getByRole('button',{name:'Download editable project'}));expect(blobs.map(b=>b.type)).toEqual(['text/html','application/json']);expect(JSON.parse(localStorage.getItem(STUDIO_KEY)).projects.story.decisions).toHaveLength(0);vi.unstubAllGlobals();
});
