import test from 'node:test';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { makeArtifact, defaultProgram, makeScene, executable, checkArtifact } from '../src/universe/engine.js';
import { htmlExport, projectExport, parseProject } from '../src/universe/exports.js';
const law={matter:true,species:true,stone:true};
const lift={id:'lift',name:'My upward water',enabled:true,match:[0,-1,2,-1],output:[2,1,0,3],mirror:true,direction:-1};
test('offline universe contains exact checked module and all assets; exported module matches live trajectory',async()=>{
 const artifact=makeArtifact({...defaultProgram(),rules:[lift]},3),world=makeScene('basin');const report=await checkArtifact(artifact,law);assert.equal(report.outcome,'pass');const html=htmlExport(artifact,world,law);assert.ok(html.includes(artifact.source));const module=await import('data:text/javascript;base64,'+Buffer.from(artifact.source).toString('base64'));const runtime=executable(artifact);let live=world,download=world;for(let i=0;i<20;i++){live=runtime.step(live);download=module.step(download);}assert.deepEqual(download,live);const dom=new JSDOM(html);assert.equal(dom.window.document.querySelectorAll('script').length,1);assert.equal(dom.window.document.querySelector('meta[name="groundwork-artifact"]').content,artifact.id);assert.equal(dom.window.document.querySelectorAll('script[src],img[src],link[href^="http"]').length,0);assert.equal(dom.window.document.querySelector('canvas').width,512);dom.window.close();
});
test('rule names cannot break out of the standalone module or become HTML',()=>{
 const name='</script><img src=x>\u2028\u2029';const a=makeArtifact({...defaultProgram(),rules:[{...lift,name}]});const html=htmlExport(a,makeScene('empty'),law),dom=new JSDOM(html);assert.equal(dom.window.document.querySelectorAll('script').length,1);assert.equal(dom.window.document.querySelectorAll('img').length,0);assert.ok(html.includes(a.source));assert.ok(!a.source.includes('</script>'));dom.window.close();
});
test('editable universe imports bounded settings only, preserving owned arrays and refusing malformed data',()=>{
 const a=makeArtifact({...defaultProgram(),rules:[lift]}),world=makeScene('hourglass'),text=projectExport(a,world,law),parsed=parseProject(text);assert.deepEqual(Object.keys(parsed),['program','world','law']);assert.deepEqual(parsed.world,world);parsed.world[0]=0;assert.notEqual(parsed.world[0],world[0]);const extra=JSON.parse(text);extra.source='arbitrary';extra.evidence={outcome:'pass'};extra.accepted=true;assert.deepEqual(Object.keys(parseProject(JSON.stringify(extra))),['program','world','law']);assert.throws(()=>parseProject(text.repeat(100)),/100 KB/);extra.world[0]=4;assert.throws(()=>parseProject(JSON.stringify(extra)),/world/);assert.throws(()=>parseProject('{"format":"other"}'));
});
test('standalone player DOM controls execute the embedded program, keep the brush ledger separate, and reset',()=>{
 const a=makeArtifact({...defaultProgram(),rules:[lift]}),world=makeScene('basin'),html=htmlExport(a,world,law);const dom=new JSDOM(html,{runScripts:'outside-only'}),win=dom.window;win.HTMLCanvasElement.prototype.getContext=()=>({fillRect(){},strokeRect(){}});win.HTMLCanvasElement.prototype.getBoundingClientRect=()=>({left:0,top:0,width:512,height:512});win.requestAnimationFrame=()=>0;const code=dom.window.document.querySelector('script').textContent.replace('export function rule','function rule').replace('export function step','function step');win.eval(code);assert.match(win.document.querySelector('#stats').textContent,/Step 0/);win.document.querySelector('#step').click();assert.match(win.document.querySelector('#stats').textContent,/Step 1/);win.document.querySelector('[data-brush="1"]').click();const canvas=win.document.querySelector('canvas');canvas.dispatchEvent(new win.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.match(win.document.querySelector('#stats').textContent,/Brush change: \+9/);win.document.querySelector('#reset').click();assert.match(win.document.querySelector('#stats').textContent,/Step 0Brush change: \+0Physics change: \+0/);dom.window.close();
});
