import React,{useState,useEffect,useRef} from 'react';
import {Stack,ArrowRight,CheckCircle,WarningCircle,DownloadSimple,ArrowCounterClockwise} from '@phosphor-icons/react';
import {Modal} from './App.jsx';
import {PEOPLE,expectedBadge,expectedShopping,lessonExecutable,lessonCurrency,lessonScope} from './lesson-engine.js';
import {LESSON_KEY,newLesson,newLessons,restoreLessons,startLesson,repairLesson,recheckLesson,proposeLesson,approveLessonChange,acceptLesson,lessonSample,lessonResult,lessonAcceptance,lessonCanAccept} from './lesson-session.js';
import './lessons.css';
const title=kind=>kind==='badge'?'Name badge':'Shopping list';
const policyLabel=policy=>({first:'First name only',full:'Full name',hide:'Hide bought items',all:'Show bought items too'}[policy]);
const short=id=>id.slice(0,10);
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function load(){let raw=null;try{raw=localStorage.getItem(LESSON_KEY);return {data:raw?restoreLessons(raw):newLessons()};}catch(error){return {data:newLessons(),recovery:{raw,message:error.message}};}}
function Badge({text,label}){return <div className="lesson-badge" aria-label={label}><span>HELLO, MY NAME IS</span><strong>{text}</strong><small>A fictional example badge</small></div>;}
function ListView({result,onBuy}){return <div className="lesson-list"><ul>{result.rows.map(row=><li key={row.id}><div><strong>{row.name}</strong><small>{row.bought?'Bought':'Still needed'}</small></div>{!row.bought&&onBuy&&<button className="btn secondary" onClick={event=>{if(event.detail<=1)onBuy(row.id);}}>Mark {row.name} bought</button>}{row.bought&&<CheckCircle size={20}/>}</li>)}</ul>{!result.rows.length&&<p className="lesson-empty">No items visible</p>}{!!result.receipt.length&&<p className="lesson-receipt">Bought: {result.receipt.join(', ')}. Hidden items stay on the list.</p>}</div>;}
function Output({kind,value,label}){return kind==='badge'?<Badge text={value.text} label={label}/>:<ListView result={value}/>;}
function Comparison({kind,expected,actual}){return <div className="lesson-comparison"><section><h3>Your rule asks for</h3><Output kind={kind} value={expected} label="Expected badge"/></section><section><h3>This version made</h3><Output kind={kind} value={actual} label="Actual badge"/></section></div>;}
export function Lessons(){
  const [loaded]=useState(load),[data,setData]=useState(loaded.data),[recovery,setRecovery]=useState(loaded.recovery),[saved,setSaved]=useState(false),[reset,setReset]=useState(false),[notice,setNotice]=useState('');
  const current=useRef(data);current.current=data;
  const s=data.lessons[data.selected],e=lessonResult(s),accepted=lessonAcceptance(s),passed=lessonCanAccept(s),witness=e?.cases.find(c=>c.outcome==='failed'),stale=!!e&&lessonCurrency(e,s.rule,s.artifact)!=='current';
  const main=useRef(null);
  useEffect(()=>{if(recovery){setSaved(false);return;}try{localStorage.setItem(LESSON_KEY,JSON.stringify(data));setSaved(true);}catch{setSaved(false);}},[data,recovery]);
  function update(fn){try{const old=current.current,next={...old,lessons:{...old.lessons,[old.selected]:fn(old.lessons[old.selected])}};current.current=next;setData(next);setNotice('');}catch(error){setNotice(error.message);}}
  function select(kind){const next={...current.current,selected:kind};current.current=next;setData(next);setNotice('');window.scrollTo(0,0);}
  function advance(fn){update(fn);window.scrollTo(0,0);main.current?.focus({preventScroll:true});}
  function exportAll(){download('groundwork-lessons.json',JSON.stringify(current.current,null,2));}
  const sample=s.artifact?lessonExecutable(s.artifact)(s.kind==='badge'?PEOPLE[s.sample]:s.sample,s.kind==='shopping'?'view':undefined):null;
  const lessonNumber=s.kind==='badge'?'01':'02';
  return <div className="beginner-app">
    <header className="lesson-topbar"><button className="lesson-brand" onClick={()=>select('badge')} aria-label="Groundwork beginner lessons"><Stack size={27}/><strong>Groundwork</strong><span>LEARN BY DOING</span></button><details className="lesson-more"><summary>More examples</summary><a href="?example=audio">Audio queue · advanced example</a><p>Your existing audio project and history are preserved.</p></details></header>
    <main className="lesson-main" ref={main} tabIndex={-1}>
      <nav className="lesson-path" aria-label="Beginner examples"><button onClick={()=>select('badge')} aria-current={s.kind==='badge'?'step':undefined}><span>1</span>Name badge</button><ArrowRight size={16}/><button onClick={()=>select('shopping')} aria-current={s.kind==='shopping'?'step':undefined}><span>2</span>Shopping list</button></nav>
      {(!saved||recovery)&&<div className="notice amber" role="alert"><div><strong>{recovery?'Saved lessons could not be restored. The original has not been overwritten.':'Lessons are not saved. Export before closing.'}</strong><button className="text-btn" onClick={exportAll}>Export current lessons</button>{recovery&&<><button className="text-btn" onClick={()=>download('groundwork-unrestored-lessons.txt',recovery.raw||recovery.message,'text/plain')}>Download original data</button><button className="text-btn" onClick={()=>setReset(true)}>Review reset options</button></>}</div></div>}
      {notice&&<p className="notice amber" role="status">{notice}</p>}
      <div className="lesson-heading"><p className="eyebrow">EXAMPLE {lessonNumber} · {s.draft?'CHANGE YOUR MIND':s.revised?'YOUR NEW RULE':'ONE SMALL PROMISE'}</p><h1>{s.phase==='done'?`${title(s.kind)} lesson finished.`:s.kind==='badge'?'Make a name badge.':'A list that follows your rule.'}</h1><p>{s.phase==='done'?'Keep exploring, or try another example.':s.kind==='badge'?'Choose what the badge should say. Then see whether the program gets it right.':'You bought the milk. The bread should still be on your list.'}</p></div>
      {s.phase==='choose'&&<>
        <div className="lesson-workbench"><section className="lesson-card"><p className="eyebrow">{s.kind==='badge'?'MEET MAYA':'YOUR TWO-ITEM LIST'}</p>{s.kind==='badge'?<><h2>Maya Chen</h2><p>A fictional guest. No personal information needed.</p><fieldset className="lesson-options"><legend>What should her badge say?</legend>{['first','full'].map(policy=><label key={policy}><input type="radio" name="badge-rule" checked={s.choice===policy} onChange={()=>update(l=>({...l,choice:policy}))}/><span>{policyLabel(policy)}</span></label>)}</fieldset></>:<><ListView result={expectedShopping('all',[false,false])}/><h2>Hide only what you bought.</h2><p>After you mark Milk bought, hide Milk. Keep Bread visible because it is still needed. Hiding is not deleting.</p></>}</section>
        <section className="lesson-card lesson-promise"><p className="eyebrow">YOUR RULE, MADE VISIBLE</p>{s.kind==='badge'?<Badge text={expectedBadge(s.choice,0).text} label="Proposed badge"/>:<><p>After marking Milk bought:</p><ListView result={expectedShopping('hide',[true,false])}/></>}<button className="btn primary" onClick={()=>advance(startLesson)}>Use this rule & check <ArrowRight size={17}/></button><p className="lesson-note">The first version has a deliberate mistake. You will use a prepared repair. No live AI service is connected.</p></section></div>
      </>}
      {s.draft&&<section className="lesson-card lesson-change" aria-label="Proposed rule change"><p className="eyebrow">A DIFFERENT PREFERENCE, NOT ANOTHER BUG</p><h2>{s.kind==='badge'?(s.draft.policy==='full'?'Would full names help here?':'Would first names feel more informal?'):'Would you prefer a different view?'}</h2><p>The previous version followed your rule. You can keep it, or choose the behavior below.</p><div className="lesson-comparison">{[s.rule,s.draft].map((rule,index)=><section key={index}><h3>{index?'Proposed':'Currently approved'} · {policyLabel(rule.policy)}</h3>{s.kind==='badge'?<div className="lesson-badge-pair">{[0,1].map(i=><div key={i}><p>{PEOPLE[i].first} {PEOPLE[i].last}</p><Badge text={expectedBadge(rule.policy,i).text}/></div>)}</div>:<><p>Milk is bought. Bread is still needed.</p><ListView result={expectedShopping(rule.policy,[true,false])}/></>}</section>)}</div><p className="lesson-note">Approving changes the rule and checks a new program. Earlier results and decisions stay in history.</p><div className="actions"><button className="btn primary" onClick={()=>advance(approveLessonChange)}>Approve new rule & check</button><button className="btn secondary" onClick={()=>update(l=>({...l,draft:null}))}>Keep my rule</button></div></section>}
      {s.phase==='result'&&!s.draft&&e&&<>
        <section className={`lesson-result ${passed?'is-passed':''}`} aria-label="Check result"><div>{passed?<CheckCircle size={24}/>:<WarningCircle size={24}/>}<div><p className="eyebrow">{stale?'FRESH CHECK NEEDED':e.outcome==='passed'?'CHECK PASSED':e.outcome==='failed'?'CHECK FOUND A MISTAKE':'CHECK INCONCLUSIVE'}</p><h2>{stale?'Check this version again.':passed?(s.revised?'A new rule. A fresh check.':'Now it follows your rule.'):witness?(s.kind==='badge'?'That is not the name you asked for.':'Bread should still be here.'):'This check could not establish a result.'}</h2><p>{stale?'The earlier result stays in history, but does not match the current checking conditions.':passed?(s.kind==='badge'?'All four fictional people matched the chosen badge rule.':'All four list states and every supported action matched the chosen rule.'):witness?(s.kind==='badge'?`For ${witness.input.first} ${witness.input.last}, compare the requested badge with the actual output.`:'Starting with Milk and Bread still needed, the check marked Milk bought. The program hid Bread too.') :e.message}</p></div></div></section>
        {witness&&!stale&&<><Comparison kind={s.kind} expected={witness.expected} actual={witness.actual}/><div className="lesson-repair"><button className="btn primary" onClick={()=>advance(repairLesson)}>Apply prepared repair & check</button><p>The program changes. Your rule stays the same.</p></div></>}
        {(stale||e.outcome==='inconclusive')&&<button className="btn secondary" onClick={()=>advance(recheckLesson)}>Check this version again</button>}
        <section className="lesson-card lesson-practice" aria-label="Live practice"><div className="lesson-section-heading"><div><p className="eyebrow">{passed?'TRY IT YOURSELF':'TRY THE CURRENT VERSION'}</p><h2>{s.kind==='badge'?'Another person, the same rule.':'Your list, ready to try.'}</h2></div><span className="tag">{policyLabel(s.rule.policy)}</span></div>{s.kind==='badge'?<div className="lesson-badge-practice"><label className="field">Example person<select value={s.sample} onChange={event=>update(l=>lessonSample(l,Number(event.target.value)))}>{PEOPLE.map((p,i)=><option key={p.id} value={i}>{p.first} {p.last}</option>)}</select></label><Badge text={sample.text} label="Live badge"/></div>:<><ListView result={sample} onBuy={action=>update(l=>lessonSample(l,action))}/><button className="text-btn" onClick={()=>update(l=>lessonSample(l,'reset'))}><ArrowCounterClockwise size={16}/>Start example again</button></>}<p className="lesson-note">This example runs the same stored program that was checked.</p></section>
        {passed&&<section className="lesson-decision" aria-label="Your decision"><div><p className="eyebrow">YOUR DECISION</p><h2>{accepted?'Accepted for this practice example.':'Is this the version you want?'}</h2><p>{lessonScope(s.kind)}</p><p className="lesson-note">A passing check does not choose your preference. This is a practice decision, not approval for real-world use.</p></div><div className="lesson-decision-actions">{!accepted&&<><button className="btn primary" onClick={()=>update(acceptLesson)}>Accept this practice version</button><button className="btn secondary" onClick={()=>advance(l=>({...l,phase:'done'}))}>Leave undecided</button></>}<button className="btn secondary" onClick={()=>advance(l=>({...l,phase:'done'}))}>Finish this lesson</button></div></section>}
        {passed&&<section className="lesson-next"><div><p className="eyebrow">OPTIONAL · A SECOND LESSON</p><h2>What if you change your mind?</h2><p>The code can be right even when you want a different result.</p></div><button className="btn secondary" onClick={()=>advance(proposeLesson)}>Try changing the rule <ArrowRight size={17}/></button></section>}
      </>}
      {s.phase==='done'&&<section className="lesson-card lesson-finished"><CheckCircle size={30}/><h2>{s.revised?'You explored both kinds of change.':'You fixed the program, not the rule.'}</h2><p>{s.revised?'First, the prepared repair made the code follow your rule. Later, you chose a different rule and checked a new version.':'The first lesson is finished. Changing the requirement is a separate, optional lesson.'}</p><p className="lesson-decision-state">Your decision: {accepted?'accepted for this practice version':'left undecided'}</p><div className="actions">{s.kind==='badge'?<button className="btn primary" onClick={()=>select('shopping')}>Try the shopping list <ArrowRight size={17}/></button>:<button className="btn primary" onClick={()=>select('badge')}>Back to the name badge</button>}<button className="btn secondary" onClick={()=>update(l=>({...l,phase:'result'}))}>Return to this example</button></div>{!s.revised&&<button className="text-btn" onClick={()=>advance(proposeLesson)}>Optional: try changing this rule</button>}</section>}
      {s.rule&&<details className="lesson-details"><summary>What was checked? Source & history</summary><p>{lessonScope(s.kind)}</p><p>Rule v{s.rule.revision} · program i{s.artifact.revision}. JavaScript, prepared code generation, the independent reference tables, and checker are trusted. This is not an independent mathematical proof. Browser rendering is checked separately. History is editable browser-local storage, not a signed audit trail; hashes identify artifacts.</p><button className="btn secondary" onClick={()=>download(`${s.kind}-i${s.artifact.revision}.mjs`,s.artifact.source,'text/javascript')}>Download exact module</button><details><summary>Current rule and source</summary><pre>{JSON.stringify(s.rule,null,2)}</pre><pre>{s.artifact.source}</pre></details><h3>Earlier checks stay here</h3>{[...s.evidence].reverse().map(report=><article key={report.id} className="lesson-history"><h4>Rule v{report.rule.revision} / program i{report.artifact.revision}</h4><p><span className="tag">{report.outcome}</span> <span className="tag">{lessonCurrency(report,s.rule,s.artifact)}</span> · {report.cases.length} cases checked · {s.acceptances.some(a=>a.evidenceId===report.id)?'Accepted historically for this practice example':'No acceptance recorded'}</p><details><summary>Inspect this result and its artifacts</summary><p>Rule {short(report.rule.id)} · source {short(report.artifact.id)}</p><pre>{JSON.stringify(report,null,2)}</pre></details></article>)}<details><summary>Approvals and changes</summary><pre>{JSON.stringify({approvals:s.approvals,changes:s.changes,decisions:s.acceptances},null,2)}</pre></details></details>}
      <footer className="lesson-footer"><span>{saved?'Progress saved in this browser':'Progress not saved'}</span><button className="text-btn" onClick={exportAll}><DownloadSimple size={15}/>Export lessons</button><button className="text-btn" onClick={()=>setReset(true)}>Restart this example</button></footer>
    </main>
    {reset&&<Modal title={recovery?'Replace unrestored lessons?':`Restart the ${title(s.kind).toLowerCase()}?`} onClose={()=>setReset(false)}><p>{recovery?'The unreadable saved data will be replaced with new lessons. Download the original data first if you need it.':'This clears this example’s rules, checks, and decisions. The other lesson and your audio project are preserved.'}</p><button className="btn secondary" onClick={exportAll}>Export lessons first</button><button className="btn secondary" onClick={()=>setReset(false)}>Keep working</button><button className="btn primary" onClick={()=>{if(recovery){const next=newLessons();current.current=next;setData(next);setRecovery(null);}else update(l=>newLesson(l.kind));setReset(false);window.scrollTo(0,0);}}>Restart example now</button></Modal>}
  </div>;
}
