import React,{useEffect,useMemo,useRef,useState} from 'react';
import {CELL_NAMES,makeArtifact,makeScene,executable,capturePatch,matchingCount,countCells,checkArtifact,interruptedEvidence,currency,canAdopt} from './engine.js';
import {WorldCanvas,CellPatch} from './WorldCanvas.jsx';
import {htmlExport,projectExport,parseProject} from './exports.js';
import {UNIVERSE_KEY,clone,freshSession,loadSession,timeline,checkpoint} from './session.js';
import {digest} from '../engine.js';
import './universe.css';
const DIRECTIONS=['↓ Down','← Left','↑ Up','→ Right'];
const POSITIONS=['top left','top right','bottom left','bottom right'];
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const uid=()=>globalThis.crypto?.randomUUID?.()||`rule-${Date.now()}-${Math.random().toString(36).slice(2)}`;
function witnessSummary(w){
 const before=[1,2,3].map(v=>w.before.filter(c=>c===v).length),after=[1,2,3].map(v=>w.after.filter(c=>c===v).length),totalBefore=before.reduce((a,b)=>a+b,0),totalAfter=after.reduce((a,b)=>a+b,0);
 if(w.property==='matter')return `${totalBefore} grain${totalBefore===1?'':'s'} → ${totalAfter} grain${totalAfter===1?'':'s'}. ${Math.abs(totalAfter-totalBefore)} ${totalAfter>totalBefore?'appeared':'disappeared'} in one encounter.`;
 if(w.property==='species')return before.map((n,i)=>n!==after[i]?`${CELL_NAMES[i+1]} ${n} → ${after[i]}`:null).filter(Boolean).join(' · ')+`. Total grains ${totalBefore===totalAfter?'stayed at '+totalBefore:`changed ${totalBefore} → ${totalAfter}`}.`;
 if(w.property==='stone')return 'A stone cell moved, appeared, or disappeared. Your promise keeps every stone position fixed.';
 return 'The executable disagreed with the independent interpreter for this encounter.';
}
function UniverseWorkspace({storageKey,accountControls}){
 const initial=useMemo(()=>loadSession(storageKey),[storageKey]);
 const [pendingSave,setPendingSave]=useState(false);
 const [session,setSession]=useState(initial.session),[recovery,setRecovery]=useState(initial.recovery),[saveError,setSaveError]=useState('');
 const [playing,setPlaying]=useState(()=>!initial.recovery&&!globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches),[selected,setSelected]=useState(()=>initial.session.draft.program.rules[0]?.id||null),[swap,setSwap]=useState(-1),[mode,setMode]=useState('sand'),[direction,setDirection]=useState(0),[showField,setShowField]=useState(false),[brushSize,setBrushSize]=useState(2),[advanced,setAdvanced]=useState(false),[notice,setNotice]=useState(''),[reviewed,setReviewed]=useState(false),[dialog,setDialog]=useState(null),[proposal,setProposal]=useState(null),[imported,setImported]=useState(null),[witnessReplay,setWitnessReplay]=useState(null);
 const [pendingScene,setPendingScene]=useState('basin');
 const [captured,setCaptured]=useState(null),[captureFrozen,setCaptureFrozen]=useState(null);
 const modalRef=useRef(null),persisted=useRef(null),gesture=useRef(null);
 const latest=useRef(session);latest.current=session;const recoveryRef=useRef(recovery);recoveryRef.current=recovery;const job=useRef(null),generation=useRef(0),alive=useRef(true);
 useEffect(()=>{alive.current=true;const flush=()=>{if(!recoveryRef.current)try{localStorage.setItem(storageKey,JSON.stringify(latest.current));}catch{/* Save failure is surfaced by the regular persistence effect. */}};window.addEventListener('pagehide',flush);return()=>{flush();window.removeEventListener('pagehide',flush);alive.current=false;generation.current++;job.current?.abort();};},[storageKey]);
 useEffect(()=>{if(recovery)return;const structural=persisted.current&&['current','draft','law','lawRevision','seed','reports','decisions','history','running'].every(k=>persisted.current[k]===session[k]);const save=()=>{try{localStorage.setItem(storageKey,JSON.stringify(session));persisted.current=session;setPendingSave(false);setSaveError('');}catch{setPendingSave(false);setSaveError('This workshop is not saved. Download your editable project before closing.');}};if(structural){setPendingSave(true);const timer=setTimeout(save,350);return()=>clearTimeout(timer);}save();},[session,storageKey,recovery]);
 useEffect(()=>{if(!dialog)return;const previous=document.activeElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';modalRef.current?.focus();const key=e=>{if(e.key==='Escape'){setDialog(null);return;}if(e.key!=='Tab')return;const els=modalRef.current?.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),a[href]');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===modalRef.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=overflow;previous?.focus();};},[dialog]);
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setSession(s=>s.step>=80?(setPlaying(false),s):({...s,step:s.step+1})),130);return()=>clearInterval(timer);},[playing]);
 const currentFrames=useMemo(()=>timeline(session.current.artifact,session.seed),[session.current.artifact,session.seed]);
 const trialFrames=useMemo(()=>session.current.artifact.id===session.draft.id?currentFrames:timeline(session.draft,session.seed),[session.draft,currentFrames,session.current.artifact.id,session.seed]);
 const currentWorld=currentFrames[session.step],trialWorld=trialFrames[session.step],rule=session.draft.program.rules.find(r=>r.id===selected)||null;
 const comparing=session.current.artifact.id!==session.draft.id||mode==='field';
 const report=session.reports.at(-1),isCurrent=report&&currency(report,session.draft,session.law,session.lawRevision)==='current';
 const adoptable=report&&canAdopt(report,session.draft,session.law,session.lawRevision)&&!session.running;
 const matches=useMemo(()=>rule?matchingCount(session.draft,trialWorld,rule.id):0,[session.draft,trialWorld,rule]);
 const difference=useMemo(()=>trialFrames.findIndex((w,i)=>w.some((v,j)=>v!==currentFrames[i][j])),[currentFrames,trialFrames]);
 const counts=countCells(trialWorld),currentCounts=countCells(currentWorld);
 const example=rule?rule.match:null;
 const after=rule?rule.output.map(v=>v<4?example[v]:v-4):null;
 function interrupt(s,message){if(!s.running)return s;job.current?.abort();generation.current++;return {...s,running:null,reports:[...s.reports,interruptedEvidence(s.draft,s.law,{lawRevision:s.lawRevision,message,checked:s.running.checked})]};}
 function editProgram(program,label,seed=currentWorld,recordHistory=true){setPlaying(false);setReviewed(false);setWitnessReplay(null);setSession(s=>{s=interrupt(s,'Check interrupted because the program changed.');return {...s,draft:makeArtifact(program,s.draft.revision+1),seed:seed.slice(),step:0,history:recordHistory?[...s.history,checkpoint(s,label)]:s.history};});}
 function editRule(patch,label='Edited a local rule'){if(!rule)return;const program=clone(session.draft.program);program.rules=program.rules.map(r=>r.id===rule.id?{...r,...patch}:r);editProgram(program,label);}
 function capture(x,y,world=trialWorld,artifact=session.draft){setPlaying(false);const patch=capturePatch(artifact,world,x,y,0),result=executable(artifact).rule(patch.before,patch.context),afterWorld=world.slice();patch.indices.forEach((index,i)=>afterWorld[index]=result.cells[i]);patch.actualLocal=capturePatch(artifact,afterWorld,x,y,0).local;patch.winningRule=artifact.program.rules.find(r=>r.id===result.ruleId)?.name||'Prepared falling and spreading';patch.sourceId=artifact.id;setCaptured(patch);setCaptureFrozen(world.slice());setNotice('Captured the next even-partition interaction. Add its before-picture as a rule, then draw its outcome.');}
 function addRule(patch=captured){if(session.draft.program.rules.length>=8)return;const id=uid(),program=clone(session.draft.program);program.rules.unshift({id,name:patch?'My captured interaction':'Water goes where I choose',enabled:true,match:patch?patch.local.slice():[0,-1,2,-1],output:[0,1,2,3],mirror:!patch,direction:patch?patch.context.direction:-1});editProgram(program,'Added an editable interaction',patch&&captureFrozen?captureFrozen:currentWorld);setSelected(id);setSwap(-1);setCaptured(patch||null);setNotice('Click two cells in After to swap them. Matching encounters stay still until you change this after-picture.');}
 function goToRules(){setPlaying(false);if(!session.draft.program.rules.length)addRule(null);else if(!selected)setSelected(session.draft.program.rules[0].id);requestAnimationFrame(()=>document.getElementById('universe-rules')?.scrollIntoView?.({block:'start'}));}
 function swapCell(index){if(swap<0){setSwap(index);return;}if(index!==swap){const output=rule.output.slice();[output[index],output[swap]]=[output[swap],output[index]];editRule({output},'Swapped two original cells');}setSwap(-1);}
 function paint(indices,value,fromTrial=false){setPlaying(false);setReviewed(false);const saveCheckpoint=!gesture.current?.saved;if(gesture.current)gesture.current.saved=true;setSession(s=>{const seed=timeline(fromTrial?s.draft:s.current.artifact,s.seed,s.step)[s.step].slice();for(const i of indices)seed[i]=value;return {...s,seed,step:0,history:[...s.history,...(saveCheckpoint?[checkpoint(s,'Before manual world edit')]:[]),{at:new Date().toISOString(),label:`Brush: ${CELL_NAMES[value]} (${indices.length} cells). Manual editing is outside physics.`,indices:indices.slice(),value}]};});}
 function fieldPaint(indices,value){const program=clone(session.draft.program);indices.forEach(i=>program.field[i]=value);const saveCheckpoint=!gesture.current?.saved;if(gesture.current)gesture.current.saved=true;editProgram(program,'Painted the direction field',currentWorld,saveCheckpoint);}
 async function runCheck(){
  if(session.running)return;setReviewed(false);setWitnessReplay(null);setNotice('');const start=clone(session),token=++generation.current,controller=new AbortController();job.current=controller;
  setSession(s=>({...s,running:{checked:0,total:2048,startedAt:new Date().toISOString()}}));
  try{
   const result=await checkArtifact(start.draft,start.law,{lawRevision:start.lawRevision,signal:controller.signal,onProgress:p=>{if(alive.current&&generation.current===token)setSession(s=>({...s,running:{...s.running,...p}}));}});
   if(!alive.current||generation.current!==token)return;
   setSession(s=>({...s,running:null,reports:[...s.reports,result]}));
  }catch(error){if(!alive.current||generation.current!==token)return;setSession(s=>({...s,running:null,reports:[...s.reports,interruptedEvidence(start.draft,start.law,{lawRevision:start.lawRevision,message:`Check could not finish: ${error.message}`,checked:s.running?.checked||0})]}));}
 }
 function stopCheck(){setSession(s=>interrupt(s,'Check stopped by you. No passing result was recorded.'));}
 function adopt(){const s=latest.current,r=s.reports.at(-1);if(!reviewed||s.running||!canAdopt(r,s.draft,s.law,s.lawRevision))return;setPlaying(false);const world=trialWorld.slice(),decision={at:new Date().toISOString(),artifact:clone(s.draft),world,law:clone(s.law),lawRevision:s.lawRevision,reportId:r.id,comparisonStep:s.step,comparisonSeed:s.seed.slice(),html:htmlExport(s.draft,world,s.law)};decision.htmlDigest=digest(decision.html);setSession({...s,current:{artifact:clone(s.draft),world,law:clone(s.law),origin:'human'},seed:world,step:0,decisions:[...s.decisions,decision],history:[...s.history,checkpoint(s,'Human adopted this checked version')]});setReviewed(false);setNotice('You adopted this version. The displayed trial world is now current; its exact HTML snapshot is in history.');}
 function confirmLaw(){const s=interrupt(latest.current,'Check interrupted because promises changed.');setSession({...s,law:clone(proposal),lawRevision:s.lawRevision+1,history:[...s.history,{...checkpoint(s,'Human approved changed promises'),newLaw:clone(proposal)}]});setReviewed(false);setDialog(null);setNotice('Your changed promises are recorded. Run a new check; the earlier result stays historical.');}
 async function importFile(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;try{if(file.size>100000)throw Error('Project file exceeds 100 KB.');setImported(parseProject(await file.text()));setDialog('import');}catch(error){setNotice(`Import was not applied: ${error.message}`);}}
 function confirmImport(){const s=interrupt(latest.current,'Check interrupted by a reviewed import.');const lawChanged=JSON.stringify(s.law)!==JSON.stringify(imported.law);setSession({...s,draft:makeArtifact(imported.program,s.draft.revision+1),law:clone(imported.law),lawRevision:s.lawRevision+(lawChanged?1:0),seed:imported.world.slice(),step:0,history:[...s.history,{...checkpoint(s,'Human reviewed and imported a draft'),newLaw:clone(imported.law)}]});setPlaying(false);setSelected(null);setCaptured(null);setReviewed(false);setDialog(null);setNotice('Imported settings and world. No evidence or acceptance was imported. Run a fresh check.');}
 function replaceScene(){setPlaying(false);setReviewed(false);setCaptured(null);setSession(s=>({...s,seed:makeScene(pendingScene),step:0,history:[...s.history,checkpoint(s,'Replaced drawing with '+pendingScene+' scene; physics unchanged')]}));setDialog(null);setNotice('New starting scene. Your rules, checks, and kept versions remain. Scene editing is outside physics.');}
 function reset(){job.current?.abort();generation.current++;setSession(freshSession());setRecovery(null);setSelected(null);setCaptured(null);setReviewed(false);setPlaying(false);setDialog(null);setNotice('A fresh prepared world is ready.');}
 return <main className="universe-app">
  <header className="universe-header"><a className="universe-brand" href="/">Groundwork<span> / workshop</span></a><nav><a href="/?lesson=badge">Beginner lessons</a>{accountControls}</nav></header>
  <section className="universe-title"><div><p className="universe-eyebrow">A small world. Your rules.</p><h1>Make your own physics.</h1><p>Pour something. Change one rule. Watch a whole world behave differently.</p></div><div className="universe-title-actions"><button className="universe-primary" onClick={goToRules}>Change the physics</button><button className="universe-secondary" onClick={()=>setDialog('help')}>How this world works</button></div></section><nav className="universe-sectionnav" aria-label="Workshop sections"><a href="#universe-world">World</a><a href="#universe-rules">Rules</a><a href="#universe-check">Check & keep</a></nav>
  {recovery&&<section role="alert" className="universe-alert">Saved workshop could not be restored. The original storage is untouched; this preview is temporary. <button onClick={()=>setDialog('recovery')}>Review recovery options</button></section>}
  {saveError&&<p role="alert" className="universe-alert">{saveError}</p>}
  <div className="universe-workspace"><section id="universe-world" className="universe-stage" aria-label="World workshop">
   <div className="universe-toolbar"><div className="universe-toolgroup" aria-label="World tools">{[['sand','Sand'],['water','Water'],['stone','Stone'],['erase','Erase'],['inspect','Capture'],['field','Direction']].map(([value,label])=><button key={value} aria-pressed={mode===value} onClick={()=>{setMode(value);setPlaying(false);if(value==='field')setShowField(true);}}>{label}</button>)}</div><label className="universe-compact">Brush <select aria-label="Brush size" value={brushSize} onChange={e=>setBrushSize(Number(e.target.value))}><option value={1}>1 cell</option><option value={2}>2 cells</option><option value={4}>4 cells</option></select></label><label className="universe-compact">Scene <select aria-label="New scene" value="" onChange={e=>{if(e.target.value){setPendingScene(e.target.value);setDialog('scene');}}}><option value="">Choose a starting scene…</option><option value="basin">Sand and water basin</option><option value="hourglass">Hourglass</option><option value="empty">Empty space</option></select></label></div>
   {mode==='field'&&<div className="universe-fieldtools"><label>Paint direction <select value={direction} onChange={e=>setDirection(Number(e.target.value))}>{DIRECTIONS.map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label><p>The arrow rotates each encounter into the rule’s down-facing frame.</p></div>}
   <div className={`universe-worlds ${!comparing?'universe-oneworld':''}`}><div><div className="universe-boardhead"><strong>Current</strong><span>{session.current.origin==='prepared'?'Prepared physics':'Your adopted physics'}</span></div><WorldCanvas world={currentWorld} field={session.current.artifact.program.field} label="Current world" mode={!comparing?mode:mode==='field'?'inspect':mode} direction={direction} onFieldPaint={fieldPaint} brushSize={brushSize} showField={showField} onPaint={(indices,value)=>paint(indices,value,false)} onCapture={(x,y)=>capture(x,y,currentWorld,session.current.artifact)} onEditStart={()=>{setPlaying(false);gesture.current={saved:false};}} onEditEnd={()=>{gesture.current=null;}}/><p className="universe-ledger">{currentCounts.matter.toLocaleString()} grains <span>sand {currentCounts.sand} · water {currentCounts.water}</span></p></div>{comparing&&<div><div className="universe-boardhead"><strong>Trial <span className="universe-draft">draft</span></strong><span>Revision {session.draft.revision}</span></div><WorldCanvas world={trialWorld} field={session.draft.program.field} label="Trial world" mode={mode} direction={direction} brushSize={brushSize} showField={showField} onPaint={(indices,value)=>paint(indices,value,true)} onFieldPaint={fieldPaint} onCapture={capture} onEditStart={()=>{setPlaying(false);gesture.current={saved:false};}} onEditEnd={()=>{gesture.current=null;}} highlight={captured?.indices||[]}/><p className="universe-ledger">{counts.matter.toLocaleString()} grains <span>sand {counts.sand} · water {counts.water}</span></p></div>}</div>
   <div className="universe-playback"><button className="universe-primary" onClick={()=>{if(session.step===80)setSession(s=>({...s,step:0}));setPlaying(!playing);}}>{playing?'Pause':session.step===80?'Replay from start':!comparing?'Play world':'Play both'}</button><button onClick={()=>{setPlaying(false);setSession(s=>({...s,step:Math.min(80,s.step+1)}));}}>Step</button><label>Same moment <input aria-label="Comparison step" type="range" min="0" max="80" value={session.step} onChange={e=>{setPlaying(false);setSession(s=>({...s,step:Number(e.target.value)}));}}/></label><output>{session.step} / 80</output></div>
   <div className="universe-comparison">{session.step===80&&<span className="universe-ended">80-step comparison finished. Replay or continue from here.</span>}<button onClick={()=>{setPlaying(false);setReviewed(false);setSession(s=>({...s,seed:trialWorld.slice(),step:0,history:[...s.history,checkpoint(s,'Manually started a new comparison from displayed trial')]}));setNotice('Both previews now start from this displayed snapshot. Your kept world and physics remain in history.');}}>{session.current.artifact.id===session.draft.id?'Continue this world':'Start a new comparison from trial'}</button><span>{!comparing?'Paint your world, then invent a rule. Edges wrap.':'Same starting snapshot. Same tick. Edges wrap.'}</span>{comparing&&<button disabled={difference<0} onClick={()=>{setPlaying(false);setSession(s=>({...s,step:difference}));}}>{difference<0?'No difference in 80 steps':`First difference · step ${difference}`}</button>}<label><input type="checkbox" checked={showField} onChange={e=>setShowField(e.target.checked)}/> Show direction field</label></div>
   <div className="universe-start"><p><strong>Start with an encounter.</strong> Pause and click the world to capture four cells, or begin with a water grain. Swap two after-cells to write a rule.</p><button disabled={session.draft.program.rules.length>=8} onClick={()=>addRule(null)}>{session.draft.program.rules.length?'New rule':'Make my first rule'}</button></div>
   {captured&&<section className="universe-capture"><div><CellPatch cells={captured.local} label="Captured encounter, facing down"/><p>Before</p></div>{captured.actualLocal&&<div><CellPatch cells={captured.actualLocal} label="Captured encounter actual next result"/><p>Actual next result</p></div>}<div><p>Captured at ({captured.x}, {captured.y}), next even partition. Field: {DIRECTIONS[captured.context.direction]}.</p>{captured.winningRule&&<p>Selected rule: {captured.winningRule}. Captured source {captured.sourceId.slice(0,8)}.</p>}<button disabled={session.draft.program.rules.length>=8} onClick={()=>addRule(captured)}>Make a rule from this encounter</button></div></section>}
  </section>
  <aside id="universe-rules" className="universe-editor" aria-label="Rule editor"><div className="universe-paneltitle"><h2>Your rules</h2><span>{session.draft.program.rules.length} / 8</span></div><p>First matching rule wins. Otherwise, ordinary falling and spreading takes over.</p>
   <div className="universe-rulelist">{session.draft.program.rules.map((r,i)=><button key={r.id} aria-pressed={selected===r.id} onClick={()=>{setSelected(r.id);setSwap(-1);setCaptured(null);}}><span>{i+1}</span>{r.name}<small>{r.enabled?'':'off'}</small></button>)}</div>
   {!rule?<div className="universe-emptyeditor"><h3>A little rule can change everything.</h3><p>Capture an encounter in the world, then draw what should happen next. Begin with a move; add rules that interact.</p><button onClick={()=>addRule(null)} disabled={session.draft.program.rules.length>=8}>Add an interaction</button></div>:<>
    <label className="universe-label">Rule name<input maxLength={60} value={rule.name} onChange={e=>editRule({name:e.target.value})}/></label>
    <div className="universe-patches"><div className="universe-patch-group"><span>Before</span><CellPatch cells={rule.match} label="Before"/></div><span aria-hidden="true">→</span><div className="universe-patch-group"><span>After</span><CellPatch cells={after} label="After: choose two cells to swap" selected={swap} onCellClick={swapCell} annotations={rule.output.map(v=>v<4?`Original ${POSITIONS[v]}`:`Write ${CELL_NAMES[v-4]}`)}/></div></div>
    <p className="universe-hint">{swap<0?'Click two After cells to swap their original tiles.':`Selected ${POSITIONS[swap]}. Choose its swap partner.`}</p><p className="universe-matchcount"><strong>{matches}</strong> encounters select this rule in the trial’s next even partition.</p>
    <div className="universe-rulerow"><label><input type="checkbox" checked={rule.enabled} onChange={e=>editRule({enabled:e.target.checked})}/> Enabled</label><button onClick={()=>{const p=clone(session.draft.program),i=p.rules.findIndex(r=>r.id===rule.id);if(i>0){[p.rules[i-1],p.rules[i]]=[p.rules[i],p.rules[i-1]];editProgram(p,'Changed rule priority');}}} disabled={session.draft.program.rules[0]?.id===rule.id}>Earlier</button><button onClick={()=>{const p=clone(session.draft.program),i=p.rules.findIndex(r=>r.id===rule.id);if(i<p.rules.length-1){[p.rules[i+1],p.rules[i]]=[p.rules[i],p.rules[i+1]];editProgram(p,'Changed rule priority');}}} disabled={session.draft.program.rules.at(-1)?.id===rule.id}>Later</button></div>
    <button className="universe-disclosure" aria-expanded={advanced} onClick={()=>setAdvanced(!advanced)}>{advanced?'−':'+'} Match, copy, transform & mirror</button>
    {advanced&&<div className="universe-advanced"><p>References read the original encounter. Reusing a reference copies it; writing a material can create, destroy, or transform grains.</p>{POSITIONS.map((name,i)=><div className="universe-cellrow" key={name}><label>Before {name}<select value={rule.match[i]} onChange={e=>{const match=rule.match.slice();match[i]=Number(e.target.value);editRule({match});}}><option value={-1}>Any material</option>{CELL_NAMES.map((n,v)=><option key={n} value={v}>{n}</option>)}</select></label><label>After {name}<select value={rule.output[i]} onChange={e=>{const output=rule.output.slice();output[i]=Number(e.target.value);editRule({output});}}>{POSITIONS.map((n,v)=><option key={n} value={v}>Original {n}</option>)}{CELL_NAMES.map((n,v)=><option key={n} value={v+4}>Write {n}</option>)}</select></label></div>)}<label><input type="checkbox" checked={rule.mirror} onChange={e=>editRule({mirror:e.target.checked})}/> Also match its horizontal mirror</label><label className="universe-label">Only in this field direction<select value={rule.direction} onChange={e=>editRule({direction:Number(e.target.value)})}><option value={-1}>Any direction</option>{DIRECTIONS.map((n,i)=><option value={i} key={n}>{n}</option>)}</select></label><div className="universe-rulerow"><button disabled={session.draft.program.rules.length>=8} onClick={()=>{const p=clone(session.draft.program),id=uid();p.rules.push({...clone(rule),id,name:`${rule.name.slice(0,50)} copy`});editProgram(p,'Duplicated a rule');setSelected(id);}}>Duplicate</button><button onClick={()=>{const p=clone(session.draft.program);p.rules=p.rules.filter(r=>r.id!==rule.id);editProgram(p,'Deleted a rule');setSelected(null);}}>Delete rule</button></div></div>}
   </>}
   <a className="universe-backtoworld" href="#universe-world">See your world change</a>
   <button className="universe-add" disabled={session.draft.program.rules.length>=8} onClick={()=>addRule(null)}>+ Add another rule</button>
  </aside></div>
  {notice&&<p role="status" className="universe-notice">{notice}</p>}
  <section id="universe-check" className="universe-evidence" aria-label="Promises and evidence"><div className="universe-promises"><p className="universe-eyebrow">Freedom with promises</p><h2>What should your world keep?</h2><ul><li>The total number of grains</li>{session.law.species&&<li>The amount of each material</li>}{session.law.stone&&<li>Stone stays in its original cells</li>}</ul><button onClick={()=>{setProposal(clone(session.law));setDialog('law');}}>Review my promises</button><p>Promise revision {session.lawRevision}. Pouring and erasing are your edits, outside physics.</p></div><div className="universe-results"><div className="universe-paneltitle"><h2>Check the actual rules</h2>{session.running?<button onClick={stopCheck}>Stop check</button>:<button className="universe-primary" onClick={runCheck}>Check my rules</button>}</div><p>256 cell arrangements × 4 directions × 2 phases. Independent expectations; the same source that runs your world.</p>
   {session.running&&<div role="status"><progress max={2048} value={session.running.checked}/><p>Checking {session.running.checked} / 2,048 actual cases…</p></div>}
   {report&&!session.running&&<div className={`universe-verdict universe-${report.outcome}`}><strong>{report.outcome==='pass'?'Checks passed':report.outcome==='fail'?'A promise needs attention':'Check incomplete'} · {isCurrent?'current':'historical — no longer current'}</strong><p>{report.message}</p><p>{report.checked.toLocaleString()} / {report.total.toLocaleString()} local cases · Engine fixtures: {report.engineTests?.outcome||'not run'} ({report.engineTests?.checked||0})</p>{report.properties.map(p=><span className="universe-property" key={p.key}>{p.label}: {p.outcome}</span>)}</div>}
   {report?.witnesses?.length>0&&<section className="universe-witness"><h3>A concrete counterexample</h3><p>This is a possible local arrangement, not necessarily one in today’s world.</p>{report.witnesses.slice(0,3).map((w,i)=><div key={i}><p><strong>{({species:'A material changed',matter:'The number of grains changed',stone:'Stone did not stay fixed',conformance:'The interpreters disagreed'})[w.property]||w.property}</strong> · {report.artifact.program.rules.find(r=>r.id===w.ruleId)?.name||'Prepared physics'}</p><p>{witnessSummary(w)}</p><div className="universe-patches"><CellPatch cells={w.before} label={`Witness ${i+1} before`}/><span>→</span><CellPatch cells={w.after} label={`Witness ${i+1} actual output`}/></div><details><summary>Exact case details</summary><p>{DIRECTIONS[w.context.direction]} · phase {w.context.phase} · rule ID {w.ruleId||'prepared physics'} · {w.mirrored?'mirrored':'direct'} match.</p><p>Expected: {JSON.stringify(w.expected)} · Observed: {JSON.stringify(w.observed)}</p></details><button onClick={()=>{const actual=executable(report.artifact).rule(w.before,w.context);setWitnessReplay({index:i,cells:actual.cells,agrees:JSON.stringify(actual.cells)===JSON.stringify(w.after)});}}>Replay witness {i+1}</button>{witnessReplay?.index===i&&<p role="status">Executed the saved source again: {witnessReplay.agrees?'the same output was reproduced.':'output differs; do not rely on this evidence.'}</p>}</div>)}</section>}
   <div className="universe-adoption"><p><strong>A check is evidence. Keeping a version is your decision.</strong> This exhausts the local domain and runs separate engine fixtures. It is not a Bend proof or a guarantee of every world, rendering, or enjoyable behavior.</p><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> I tried this version and reviewed these limits.</label><button className="universe-primary" disabled={!adoptable||!reviewed} onClick={adopt}>Use this version</button>{!adoptable&&<p className="universe-disabled-reason">{session.running?'Wait for the check to finish, or stop it.':!report?'Run a complete check of these rules first.':!isCurrent?'This result no longer applies. Check the current rules and promises again.':report.outcome==='fail'?'This version breaks a chosen promise. Edit the rule or review your promises.':'A complete passing check is needed before using this version.'}</p>}{adoptable&&!reviewed&&<p className="universe-disabled-reason">Try this version, review the limits, then tick the box.</p>}</div>
  </div></section>
  <section className="universe-keep"><div><h2>Keep your little universe.</h2><p>Offline, editable, yours. Downloads do not record acceptance.</p></div><div className="universe-downloads"><button onClick={()=>download(htmlExport(session.draft,trialWorld,session.law),'my-universe-draft.html','text/html')}>Download runnable draft</button><button onClick={()=>download(projectExport(session.draft,trialWorld,session.law),'my-universe.json','application/json')}>Download editable project</button><label className="universe-file">Import a project<input type="file" accept=".json,application/json" onChange={importFile}/></label></div></section>
  <section className="universe-record"><details><summary>Versions & evidence · {session.decisions.length} human decisions · {session.reports.length} checks</summary><p>Stored in this account’s browser workspace. Storage is editable and unsigned; it is not independent certification.</p>{session.decisions.map((d,i)=><article key={`${d.at}-${i}`}><strong>Adopted version {i+1} · {new Date(d.at).toLocaleString()}</strong><p>Source {d.artifact.id.slice(0,12)} · promise revision {d.lawRevision}</p><button onClick={()=>download(d.html,`my-universe-adopted-${i+1}.html`,'text/html')}>Download exact adopted version {i+1}</button><button onClick={()=>{editProgram(d.artifact.program,'Restored adopted version as a new draft',d.world);setNotice('Historical program and world restored as a draft. Current promises remain; check again.');}}>Restore as draft</button></article>)}{session.reports.map((r,i)=><article key={`${r.id}-${i}`}><strong>Check {i+1}: {r.outcome}</strong><p>{r.checked}/{r.total} cases · {currency(r,session.draft,session.law,session.lawRevision)} · {r.message}</p><button onClick={()=>download(JSON.stringify(r,null,2),`universe-evidence-${i+1}.json`,'application/json')}>Download evidence {i+1}</button></article>)}{session.history.map((h,i)=><div key={i}><p>{h.label} <small>{new Date(h.at).toLocaleString()}</small></p>{h.artifact&&h.world&&<button onClick={()=>{editProgram(h.artifact.program,'Restored historical draft snapshot',timeline(h.artifact,h.world,h.step||0)[h.step||0]);setNotice('Historical draft restored. Current promises remain; run a new check.');}}>Restore draft snapshot {i+1}</button>}</div>)}</details><details><summary>Exact executable source · {session.draft.id.slice(0,12)}</summary><pre>{session.draft.source}</pre></details><div className="universe-footer"><span>{!saveError&&!recovery?pendingSave?'Saving playback position…':'Saved in this browser · device-local':'Temporary workspace · not saved'}</span><a href="?archive=starters">Recover archived starter work</a><button onClick={()=>{setPlaying(false);setSession(s=>({...s,seed:s.current.world.slice(),step:0,history:[...s.history,checkpoint(s,'Returned to kept world snapshot')]}));}}>Return to kept world</button><button onClick={()=>setDialog('reset')}>Reset workshop…</button></div></section>
  {dialog&&<div className="universe-modalbackdrop"><section ref={modalRef} tabIndex={-1} className="universe-modal" role="dialog" aria-modal="true" aria-labelledby="universe-dialog-title"><h2 id="universe-dialog-title">{({scene:'Replace the starting scene?',law:'Review a change to your promises',import:'Review imported project',reset:'Start a fresh workshop?',recovery:'Recover your saved workshop',help:'Small rules, surprising worlds'})[dialog]}</h2>
   {dialog==='scene'&&<><p>This replaces the drawing with {pendingScene==='empty'?'empty space':pendingScene==='hourglass'?'an hourglass':'a sand and water basin'}. Your physics and kept versions remain. The current drawing is preserved as a restorable snapshot in history.</p><button className="universe-primary" onClick={replaceScene}>Replace drawing, keep rules</button></>}
   {dialog==='law'&&<><p>Total matter always stays protected. Relaxing a promise permits more behavior; it does not fix an implementation or validate earlier failures.</p><label><input type="checkbox" checked={proposal.species} onChange={e=>setProposal({...proposal,species:e.target.checked})}/> Keep the amount of each material</label><label><input type="checkbox" checked={proposal.stone} onChange={e=>setProposal({...proposal,stone:e.target.checked})}/> Keep stone in its original cells</label><p>Current: {session.law.species?'each material conserved':'material conversion allowed'}; {session.law.stone?'stone fixed':'stone may move'}.<br/>Proposed: {proposal.species?'each material conserved':'material conversion allowed'}; {proposal.stone?'stone fixed':'stone may move'}.</p><p>Old results and your decision remain in history. The changed promises require a new check.</p><button className="universe-primary" disabled={JSON.stringify(proposal)===JSON.stringify(session.law)} onClick={confirmLaw}>Approve changed promises</button></>}
   {dialog==='import'&&<><p>{imported.program.rules.length} rules and a 64 × 64 world will replace your draft. Your current adopted program and history remain.</p><p>Imported promises: total matter; {imported.law.species?'each material conserved':'material conversion allowed'}; {imported.law.stone?'stone fixed':'stone may move'}.</p><p>This confirms any promise changes as well. Imported projects carry no accepted evidence.</p><button className="universe-primary" onClick={confirmImport}>Approve import as draft</button></>}
   {(dialog==='reset'||dialog==='recovery')&&<><p>{dialog==='recovery'?'The original saved bytes remain untouched. Download them before starting over.':'This replaces this account’s workshop, including local history. Download a backup first if you want to retain it.'}</p><button onClick={()=>download(recovery?.raw||JSON.stringify(session,null,2),'universe-workshop-backup.json','application/json')}>Download recovery backup</button><button className="universe-primary" onClick={reset}>Start fresh and replace saved workshop</button></>}
   {dialog==='help'&&<><p>Sand and water move through a 64 × 64 world. Edges wrap. Stone borders in the starting scene make a bowl.</p><p>Each tick updates separate 2 × 2 encounters, then shifts that partition once. Your first matching rule decides an encounter; ordinary physics handles the rest. Direction arrows rotate the encounter into a down-facing frame.</p><p>Pause, capture an encounter, and swap cells in its after-picture. More controls let you match any material, copy original cells, transform materials, and combine up to eight rules. Click Play both or scrub to compare real computed futures.</p><p>The checker executes 2,048 local cases and separate engine fixtures. It can show cases your current scene has never reached. No live AI, physical fluid solver, or theorem prover is running here.</p></>}
   <button onClick={()=>setDialog(null)}>{dialog==='help'?'Back to my world':'Cancel'}</button>
  </section></div>}
 </main>;
}
export function Universe({storageKey=UNIVERSE_KEY,accountControls}){return <UniverseWorkspace key={storageKey} storageKey={storageKey} accountControls={accountControls}/>;}
